#ifndef MAIN_H
#define MAIN_H

// Ãtats principaux du robot
#define STATE_ATTENTE 0
#define STATE_ATTENTE_EN_COURS 1
#define STATE_AVANCE 2
#define STATE_AVANCE_EN_COURS 3
#define STATE_TOURNE_SUR_PLACE 4
#define STATE_TOURNE_SUR_PLACE_EN_COURS 5
#define STATE_TOURNE_SUR_PLACE_GAUCHE 6
#define STATE_TOURNE_SUR_PLACE_GAUCHE_EN_COURS 7
#define STATE_TOURNE_SUR_PLACE_DROITE 8
#define STATE_TOURNE_SUR_PLACE_DROITE_EN_COURS 9
#define STATE_TOURNE_GAUCHE 10
#define STATE_TOURNE_GAUCHE_EN_COURS 11
#define STATE_TOURNE_DROITE 12
#define STATE_TOURNE_DROITE_EN_COURS 13
#define STATE_TOURNE_GAUCHE_LEGER 14
#define STATE_TOURNE_GAUCHE_LEGER_EN_COURS 15
#define STATE_TOURNE_DROITE_LEGER 16
#define STATE_TOURNE_DROITE_LEGER_EN_COURS 17
#define STATE_AVANCE_PRUDENT 18
#define STATE_AVANCE_PRUDENT_EN_COURS 19
#define STATE_RECULE 20
#define STATE_RECULE_EN_COURS 21
#define STATE_STOP 22
#define STATE_RECULE_GAUCHE 23
#define STATE_RECULE_DROITE 24
#define STATE_TOURNE_SUR_PLACE_GAUCHE2 25
#define STATE_TOURNE_SUR_PLACE_DROITE2 26

// DÃ©tections des obstacles
#define PAS_D_OBSTACLE 0
#define OBSTACLE_EXTREME_GAUCHE 0b10000
#define OBSTACLE_GAUCHE 0b01000
#define OBSTACLE_CENTRE 0b00100
#define OBSTACLE_DROITE 0b00010
#define OBSTACLE_EXTREME_DROITE 0b00001

// Prototypes des fonctions
void OperatingSystemLoop(void);
void SetNextRobotStateInAutomaticMode();
void __delay32(unsigned long cycles);

#endif
